[app]

# (str) Title of your application
title = My Kivy App

# (str) Package name
package.name = mykivyapp

# (str) Package domain (needed for android packaging)
package.domain = org.test

# (list) Source files to include (let it blank to include all files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusion/exclusion patterns
source.include_patterns = assets/*,images/*.png

# (str) Application versioning
version = 0.1

# (list) Application requirements
# (Make sure python3, kivy, and pillow are here)
requirements = python3,kivy,pillow

# (list) Custom source folders for dependencies
#source.dirs = ''

# (list) Permissions
android.permissions = INTERNET

# (list) Supported orientations
orientation = portrait

# (list) List of service to declare
#services = 

#
# OSX Specific
#

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color
#android.presplash_color = #FFFFFF

# (list) Application android API to use
#android.api = 33

# (list) Minimum API your APK will support
android.minapi = 24

# (str) Android NDK version to use
#android.ndk = 25b

# (bool) Use Android X
android.androidx = True

# (str) The Android arch to build for, in parallel
# Supported values: armeabi-v7a, arm64-v8a, x86, x86_64
android.archs = arm64-v8a, armeabi-v7a

# (int) overrides the outgoing version code (default: autogenerated)
#android.version_code = 


[buildozer]

# (int) Log level (0 = error, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact, local or absolute
bin_dir = ./bin

# (str) Path to build directory
#build_dir = ./.buildozer

# (str) Path to package directory
#package_dir = ./.buildozer
