name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Buildozer directories
        uses: actions/cache@v3
        with:
          path: |
            .buildozer
            ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install System Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            git zlib1g-dev libncurses5-dev libncursesw5-dev \
            libffi-dev libssl-dev libltdl-dev libtool automake autoconf \
            unzip wget lld openjdk-17-jdk python3-pip cython3

      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade buildozer cython==0.29.36

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
